name: CI-Jest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.4

    - name: Monitor coverage
      uses: slavcodev/coverage-monitor-action@1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clover_file: "./coverage/clover.xml"
        threshold_alert: 70
        threshold_warning: 80
